name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build mod with Gradle
        run: ./gradlew build

      - name: Upload built mod (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
